# Generated by Django 3.2.9 on 2021-12-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('discription', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('summury', models.CharField(max_length=100)),
                ('discount', models.BooleanField()),
            ],
        ),
    ]
